# Deployment role for standard apps.
# Brought to you by Blacklight - http://www.blacklight.co.za/.
# Developer: Zander Janse van Rensburg <zjvren@geevcookie.com>
# License: MIT
#
# Handles the deployment based on the strategy specified.
---
- name: Get local path.
  local_action: shell pwd
  register: local_path
  ignore_errors: true

- name: RSync deploy.
  synchronize: src={{ local_path.stdout }}{{ deploy_local_root }} dest={{ deploy_root_dir }}/releases/{{ release_version.stdout }} times=no recursive=yes perms=no owner=no group=no
  when: deploy_strategy == "rsync" and local_path|success
  ignore_errors: true
  register: deployed

- name: Git deploy.
  git: repo={{ deploy_repo }} dest={{ deploy_root_dir }}/releases/{{ release_version.stdout }} version={{ deploy_branch }}
  when: deploy_strategy == "git" and local_path|success
  ignore_errors: true
  register: deployed

- name: SVN deploy.
  subversion: repo={{ deploy_repo }} dest={{ deploy_root_dir }}/releases/{{ release_version.stdout }} revision={{ deploy_branch }}
  when: deploy_strategy == "svn" and local_path|success
  ignore_errors: true
  register: deployed

- name: Mercurial deploy.
  hg: repo={{ deploy_repo }} dest={{ deploy_root_dir }}/releases/{{ release_version.stdout }} revision={{ deploy_branch }}
  when: deploy_strategy == "mercurial" and local_path|success
  ignore_errors: true
  register: deployed
